language: node_js   # 设置语言
node_js: stable     # 设置相应版本

cache:
  apt: true
  directories:
  - node_modules               # 缓存不经常更改的内容

before_install:
  - export TZ='Asia/Shanghai'         # 更改时区
  - npm install hexo-cli -g           # 安装hexo环境
  #- chmod +x ./auto_deploy_script.sh  # 为shell文件添加可执行权限

install:
  - npm install                    # 安装hexo及插件
  - npm rebuild node-sass --force  #该命令是根据构建失败的日志提示添加的

script:
  - hexo clean
  - hexo g
  - hexo g

after_script:
  #- ./auto_deploy_script.sh
  #- set -ev
  #- git clone https://${GH_REF} .deploy_git
  #- cd .deploy_git
  #- git checkout master
  #- cd ../
  #- mv .deploy_git/.git/ ./public/

  - cd ./public
  - git init
  - git config user.name "airbirdx"
  - git config user.email "mqliutong@163.com"
  - git add .
  - git commit -m "travis-ci auto deploy at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master           # GitHub 
  - git push --force --quiet "https://airbird:${CD_TOKEN}@${CD_REF}" master:master   # Coding.net 

branches:
  only:
  - master   # 这里替换你要监听的分支

env:
 global:
   # Github Pages
   - GH_REF: github.com/airbirdx/airbirdx.github.io.git  # GitHub     # 这里替换你的github仓库地址
   - CD_REF: git.coding.net/airbird/airbird.git          # Coding.net # 这里替换你的coding仓库地址
