language: node_js
node_js: stable

addons: # Travis CI建议加的，自动更新api
  apt:
    update: true

cache:
  directories: 
  - node_modules # 缓存 node_modules

install:
- npm install # 初次安装，在CI环境中，执行安装npm依赖

script:
- hexo clean
- hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "airbirdx"
  - git config user.email "mqliutong@163.com"
  - git add .
  - git commit -m "travis-ci auto deploy at `date +"%Y-%m-%d %H:%M"`"
  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://airbird:${CD_TOKEN}@${CD_REF}" master:master

branches:
  only:
  - master   # 这里替换你要监听的分支

env:
 global:
   # Github Pages
   - GH_REF: github.com/airbirdx/airbirdx.github.io.git  # 这里替换你的github仓库地址
   # Coding Pages
   - CD_REF: git.coding.net/airbird/airbird.git          #这里替换你的coding仓库地址
